apiVersion: v2
name: k8s-images-manager
description: A Helm chart for Kubernetes
version: 0.1.0
appVersion: 0.1.0
icon: "https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png"
