apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.server.fullname" . }}
  labels:
    {{- include "chart.server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: web
      protocol: TCP
      name: web
  selector:
    {{- include "chart.server.selectorLabels" . | nindent 4 }}
