name: Build agent

on:
  pull_request:
    paths:
      - "webapp/**"
      - ".github/workflows/master-docker-webapp.yml"

permissions:
  contents: write
  packages: write
  issues: write
  id-token: write

jobs:
  build-binary:
    name: "Build agent binary"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Install OpenSSL dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev
      - uses: mlugg/setup-zig@v2
      - uses: sigstore/cosign-installer@v4.0.0
      - uses: anchore/sbom-action/download-syft@v0.22.1
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Compile with goreleaser and publish release
        uses: goreleaser/goreleaser-action@v7
        with:
          args: release --clean --snapshot
          version: "~> v2"
          workdir: agent
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
